<a href="https://colab.research.google.com/github/yashborhade-gif/221A019_NLP_EXPRRIMENTS/blob/main/NLP_EXP_NO_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
from nltk.corpus import twitter_samples
import matplotlib.pyplot as plt
import random

In [ ]:
#download twitter sample dataset
nltk.download('twitter_samples')

[nltk_data] Downloading package twitter_samples to /root/nltk_data...
[nltk_data]   Unzipping corpora/twitter_samples.zip.

True

In [ ]:

import nltk
from nltk.corpus import twitter_samples

In [ ]:

#load the dataset
tweets = twitter_samples.strings()
type(tweets)

list

In [ ]:
len(tweets)

30000

In [ ]:
import pandas as pd
all_tweets=pd.DataFrame(tweets,columns = ["Tweets"])
all_tweets.head()

                                              Tweets
0                                hopeless for tmr :(
1  Everything in the kids section of IKEA is so c...
2  @Hegelbon That heart sliding into the waste ba...
3  “@ketchBurning: I hate Japanese call him "bani...
4           Dang starting next week I have "work" :(

In [ ]:

"len of first",len(tweets[0])

('len of first', 19)

In [ ]:
twitter_samples.fileids()

['negative_tweets.json', 'positive_tweets.json', 'tweets.20150430-223406.json']

In [ ]:
#select the set of pos and neg
positive_tweets = twitter_samples.strings('positive_tweets.json')
negative_tweets = twitter_samples.strings('negative_tweets.json')

In [ ]:
len(positive_tweets)

5000

In [ ]:
len(negative_tweets)

5000

In [ ]:
positive_tweets=pd.DataFrame(positive_tweets, columns=["Positive "])
positive_tweets['Sentiments']='positive'
positive_tweets.tail()

                                              Positive  Sentiments
4995  @chriswiggin3 Chris, that's great to hear :) D...   positive
4996  @RachelLiskeard Thanks for the shout-out :) It...   positive
4997            @side556 Hey!  :)  Long time no talk...   positive
4998  @staybubbly69 as Matt would say. WELCOME TO AD...   positive
4999  @DanielOConnel18 you could say he will have eg...   positive

In [ ]:
negative_tweets=pd.DataFrame(negative_tweets, columns=['Negative Tweets'])
negative_tweets['Sentiments']='Negative'
negative_tweets.tail()

                                        Negative Tweets Sentiments
4995               I wanna change my avi but uSanele :(   Negative
4996                         MY PUPPY BROKE HER FOOT :(   Negative
4997           where's all the jaebum baby pictures :((   Negative
4998  But but Mr Ahmad Maslan cooks too :( https://t...   Negative
4999  @eawoman As a Hull supporter I am expecting a ...   Negative

In [ ]:
tweets=pd.concat([positive_tweets,negative_tweets],ignore_index= False)
tweets=tweets.sample(frac=1).reset_index(drop=True)
tweets

,Positive,Sentiments,Negative Tweets
0,Hello :) Get Youth Job Opportunities follow &g...,positive,NaN
1,Rape time at it’s best :D http://t.co/fC5U1Tus...,positive,NaN
2,NaN,Negative,@luke_brooks @YouTube come back to cologne ple...
3,NaN,Negative,The taxi driver thought me and Sophie worked f...
4,NaN,Negative,@threecheeese @Jutalkingtomeh I can't tomorrow...
...,...,...,...
9995,NaN,Negative,At the hospital :(
9996,NaN,Negative,@R_steeez12 really sad I didn't get to see you...
9997,NaN,Negative,Garden update: my trees are gone :( http://t.c...
9998,playing Dota 2 :D,positive,NaN
9999,NaN,Negative,@TheUselessThree @IKyaa_ I wanna duo :(

In [ ]:
tweets[tweets['Sentiments']=='positive'].value_counts().sum()
tweets[tweets['Sentiments']=='Negative'].value_counts().sum()

np.int64(0)